name: Tests

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'klld/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'klld/**'

jobs:
  test-ubuntu:
    name: test-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install calibre
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Download 1984 ebook
        run: wget https://www.planetebook.com/free-ebooks/1984.mobi

      - name: Add 1984 to library
        run: |
          mkdir ~/Calibre\ Library
          calibredb add 1984.mobi --with-library ~/Calibre\ Library
          rm 1984.mobi

      - name: Build plugin
        run: |
          ./data/dump_lemmas.sh
          zip -r worddumb.zip * -x@exclude.lst

      - name: Add plugin
        run: calibre-customize -a worddumb.zip

      - name: Get calibre python version
        run: echo "CALIBRE_PY=$(calibre-debug -c 'import platform; print(".".join(platform.python_version_tuple()[:2]))')" >> $GITHUB_ENV

      - name: Restore dependencies and Wikipedia cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.config/calibre/plugins/worddumb-libs-py${{ env.CALIBRE_PY }}
            ~/.config/calibre/plugins/worddumb-wikipedia
          key: ${{ runner.os }}-${{ hashFiles('data/spacy.json') }}-${{ env.CALIBRE_PY }}

      - name: Run test
        run: cd tests && calibre-debug test.py

  test-macos:
    name: test-macos
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install calibre
        run: brew install calibre

      - name: Download 1984 ebook
        run: wget https://www.planetebook.com/free-ebooks/1984.mobi

      - name: Add 1984 to library
        run: |
          mkdir ~/Calibre\ Library
          calibredb add 1984.mobi --with-library ~/Calibre\ Library
          rm 1984.mobi

      - name: Build plugin
        run: |
          ./data/dump_lemmas.sh
          zip -r worddumb.zip * -x@exclude.lst

      - name: Add plugin
        run: calibre-customize -a worddumb.zip

      - name: Run test
        run: cd tests && calibre-debug test.py

  test-windows:
    name: test-windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install calibre and wget
        run: |
          choco install calibre wget
          echo "/C/Program Files/Calibre2" >> $GITHUB_PATH

      - name: Download 1984 ebook
        run: wget https://www.planetebook.com/free-ebooks/1984.mobi

      - name: Add 1984 to library
        run: |
          mkdir ~/Calibre\ Library
          calibredb add 1984.mobi --with-library ~/Calibre\ Library
          rm 1984.mobi

      - name: Build plugin
        run: |
          ./data/dump_lemmas.sh
          7z a -x@exclude.lst -x!.* -tzip worddumb.zip

      - name: Add plugin
        run: calibre-customize -a worddumb.zip

      - name: Get calibre python version
        run: echo "CALIBRE_PY=$(calibre-debug -c 'import platform; print(".".join(platform.python_version_tuple()[:2]))')" >> $GITHUB_ENV

      - name: Restore dependencies and Wikipedia cache
        uses: actions/cache@v2
        with:
          path: |
            ~/AppData/Roaming/calibre/plugins/worddumb-libs-py${{ env.CALIBRE_PY }}
            ~/AppData/Roaming/calibre/plugins/worddumb-wikipedia
          key: ${{ runner.os }}-${{ hashFiles('data/spacy.json') }}-${{ env.CALIBRE_PY }}

      - name: Run test
        run: cd tests && calibre-debug test.py
