name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install calibre
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Download 1984 ebook
        run: wget https://www.planetebook.com/free-ebooks/1984.mobi

      - name: Add 1984 to library
        run: |
          mkdir ~/Calibre\ Library
          calibredb add 1984.mobi --with-library ~/Calibre\ Library

      - name: Install python dependencies
        run: bash install_nltk.sh

      - name: Install redis
        run: |
          sudo apt update
          sudo apt install redis -y
          sudo systemctl stop redis

      - name: Build plugin
        run: |
          zip -r worddumb.zip *
          zip -r worddumb.zip . -i@include.lst

      - name: Add plugin
        run: calibre-customize -a worddumb.zip

      - name: Run test
        run: |
          cd tests
          calibre-debug test.py
